params:
  seed: ${...seed}

  algo:
    name: a2c_continuous_moe
  
  experts:
    expert1: 
      name: 'a1_run_test32'
      checkpoint: '/home/mj/IsaacGymEnvs/isaacgymenvs/runs/a1_run_test32/nn/a1_run_test32.pth' #abs path 
      config: '/home/mj/IsaacGymEnvs/isaacgymenvs/runs/a1_run_test32/config.yaml'
    expert2: 
      name: 'a1_run_test32'
      checkpoint:  '/home/mj/IsaacGymEnvs/isaacgymenvs/runs/a1_run_test32/nn/a1_run_test32.pth' #abs path 
      config: '/home/mj/IsaacGymEnvs/isaacgymenvs/runs/a1_run_test32/config.yaml'
    env_info:
      actions_num: 12
      agent: 1
      value_size: 1
    model:
      name: continuous_a2c_logstd
      

  model:
    name: continuous_a2c_logstd

  network:
    name: cnn_gating_network # actor_critic
    separate: False

    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0. # std = 1.
        fixed_sigma: True

    cnn:
      type: conv2d
      activation: relu
      initializer:
        name: default
      regularizer:
        name: 'None'
      num_channels: 1
      image_width: 50
      image_height: 50
      convs:    
        - filters: 32
          kernel_size: 5
          strides: 2
          padding: 2
          pooling:
            type: max
            kernel_size: 2
            strides: 2
            padding: 0
        - filters: 64
          kernel_size: 3
          strides: 2
          padding: 1
          pooling:
            type: max
            kernel_size: 2
            strides: 2
            padding: 0
        - filters: 128
          kernel_size: 3
          strides: 2
          padding: 1
          pooling:
            type: None
            
    mlp:
      units: [256, 128, 64]
      activation: elu
      d2rl: False

      initializer:
        name: default
      regularizer:
        name: None

  load_checkpoint: ${if:${...checkpoint},True,False} # flag which sets whether to load the checkpoint
  load_path: ${...checkpoint} # path to the checkpoint to load

  config:
    name: ${resolve_default:A1,${....experiment}}
    full_experiment_name: ${.name}
    env_name: rlgpu
    ppo: True
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    num_actors: ${....task.env.numEnvs}
    reward_shaper:
      scale_value: 1.0
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    e_clip: 0.2
    entropy_coef: 0.0
    learning_rate: 8.e-5 # overwritten by adaptive lr_schedule
    lr_schedule: adaptive
    kl_threshold: 0.008 # target kl for adaptive lr
    truncate_grads: True
    grad_norm: 1.
    horizon_length: 24
    minibatch_size: 768 # 2048
    mini_epochs: 5
    critic_coef: 2
    clip_value: True
    seq_len: 4 # only for rnn
    bounds_loss_coef: 0.001

    max_epochs: 6000
    save_best_after: 200
    score_to_win: 1000000
    save_frequency: 50
    print_stats: True
    
    #env_info:
     # value_size: 2
      
